col_dict = {
    'ttyp': "track_type", 
    'pfil': "db_file", 
    'tsng': "title", 
    'tart': "artist", 
    'talb': "album", 
    'tgen': "genre", 
    'tlen': "length", 
    'tsiz': "file_size", 
    'tbit': "bitrate",
    'tsmp': "sample_rate", 
    'tbpm': "bpm", 
    'tgrp': "grouping", 
    'tadd': "date_added", 
    'tcor': "corrupt_desc", 
    'tiid': "tiid", 
    'uadd': "time_added_32bit", 
    'ulbl': "label_color", 
    'utme': "unk_ctme",
    'ufsb': "file_size_bytes", 
    'sbav': "sbav", 
    'bhrt': "bhrt", 
    'bmis': "missing_bool", 
    'bply': "bply", 
    'blop': "blop", 
    'bitu': "bitu", 
    'bovc': 'bovc', 
    'bcrt': "corrupt_bool",
    'bwlb': 'bwlb', 
    'bwll': 'bwll', 
    'buns': 'buns', 
    'bbgl': 'bbgl', 'bkrk': "bkrk", 'tcom': "comment", 'utkn': "track_bum", 'tkey': "key",
       'tlbl': "label", 'ttyr': "year", 'udsc': "disc_num", 'tcmp':"composer", 'utpc': 'utpc', 'trmx': "remixer"
}